### ISSUE TITLE
Does not work on my machine

### ISSUE THREAD

**Issue by Vaults** [bf-enterprise-solutions/ed.bf#1]
Dear employee of BF Enterprise Solutions,

I hope this message finds you well. We're a long time and happy customer and have made frequent use of your service. The announcement of ed.bf was quite exciting for us as we could expand our UNIX toolset based on modern technology with more memory safety and portability.

Unfortunately, we have not been able to get bf.ed to work. We run a custom BF interpreter (for readability reasons) in our ecosystem and the developer we have can more easily share knowledge with the developer we have. If possible, we would like you to take a look at our interpreter and our Node-based environment (we're still working on migrating to AWS serverless of course) and see if there's anything we can improve on our end. Perhaps we have misread some implementation details that are necessary for full BF support.

Although we have a mature and battle-tested test harness of a whopping 7 unit tests (!!!), there's obviously room for risk and we are therefore reaching out.

The problem we have when running ed.bf is that it does print the Copyright statement as such:
```
ed.bf version 1.8.3-alpha

Copyright (C) 2021-2023 Artyom Bologov
Copyright (C) 2023-present Brainfuck Enterprise Solutions Ltd.

ed.bf is provided as is, with absolutely no warranty, under the terms
of double BSD+PATENTS license. See the LICENSE, PATENTS, and
TERMS-OF-SERVICE (only relevant for commercial use) for more
information.
```

We regret to inform you that after that point input is impossible and the program outputs nothing else. We have tested input in our system by testing simple cat-like programs like `+[>,+.<]`, which fully worked as expected on keystroke. Also, line-by-line instead of character-by-character input was tested on ed.bf but that was not working however.

We have an open-source implementation at: https://github.com/Vaults/snippets/blob/master/src/brainfuckInterface.js

We excitedly await your response,
Vaults

**Comment by aartaka** [comment]
Dear Vaults,

It is a pleasure to see that you find use for our products. It is a pity that ed.bf does not meet your expectations, though. We are commited to fixing this problem so that you and other our users can enjoy the increased productivity ed.bf offers.

However, we'd need more details to properly address that ticket. Would you please tell us the setup of your interpreter:
- Does it support cell wraparound?
- Does it support tape wraparound?
- Is input/output done by line, char, or otherwise?
- What is the cell size?
- Can your interpreter run other Brainfuck Enterprise Solutions
  products, like [meta.bf™ REPL](https://github.com/bf-enterprise-solutions/meta.bf)™?

More details on exact misbehavior will be appreciated too:
- Does invoking = print nothing?
- Does it exit right after copyright notice printing?

Notice that we aim to make our products to work on a wide range of machines, but we also set our standards for programmer productivity and program portability high enough. In line with that, our software requires a modern BF compiler/interpreter to work properly.

Our testing team uses two benchmark implementations that have proven themselves reliable enough: [Project Nayuki Brainfuck JavaScript Interpreter](https://www.nayuki.io/page/brainfuck-interpreter-javascript) and [BES-bootstrapping Sade™ Compiler](https://github.com/bf-enterprise-solutions/meta.bf). You might look into these and repurpose them for your project so that all of our products run smoothly on your hardware.

Thank you for choosing high-quality software making the world a better place.
Artyom Bologov, head of Relations, Brainfuck Enterprise Solutions.

**Comment by Vaults** [comment]
Hi Artyom,

I'm honored to be in contact with the head of relations of the company. The quick response is very appreciated and only speaks for the high quality service Brainfuck Enterprise Solutions offers. We have done some research and have answers to the given questions:

* The implementation does support cell wraparound
* The implementation does not support tape wraparound (however an implementation on 30000 cells was tested and found insufficient as well)
* The output is done by char. The input has been tested with both lines and chars.
* The cells are 8-bit
* Unfortunately, meta.bf™ REPL™ had exactly the same issue.

About the detailed misbehavior:
* Unfortunately invoking any command is not possible. The program does not accept any input whatsoever and only a static copyright screen is available. The same behavior is seen in running meta.bf™ REPL™©.
* The program "halts", although what it is working on has not been analyzed on our part yet. We have to close the process manually, when other applications reach the end of the interpreted BF code, the program normally terminates.

Hopefully this will be enough information to debug the issue further and increase portability. I also understand an issue like this is out of scope for your dev team. We may look at doing our own interpretation of the Project Nayuki business logic.

Kind regards,
Vaults

**Comment by aartaka** [comment]
Indeed, such a runtime issue is beyond the scope of Open Source Standard Support (see Terms of Service distributed with the software). In case your organization signed up for Premium Support, contact the Designated Contact for them to debug the issue on the side of the company.

Your issues are noted, though. We will get back to them while preparing for the next release and in case we decide to increase the range of supported software/hardware.

Closing this ticket.

Thanks,
Artyom
